### ISSUE TITLE
proxy settings not used, security question

### ISSUE THREAD

**Issue by tlorenz-reply** [blackducksoftware/blackduck-common#327]
this invocation seems not to use the configured proxy (--blackduck.proxy.host/port) when invoking detect.sh which leads to a java.net.ConnectException: Connection timed out (Connection timed out) in a proxy environment:

https://github.com/blackducksoftware/blackduck-common/blob/07a0feda00265401f7bf3e107aa7c0f2f7fab502/src/main/java/com/synopsys/integration/blackduck/codelocation/signaturescanner/command/ScannerZipInstaller.java#L161

And:
Is it really a good idea to download a certificate from the server and store it in the keystore?

**Comment by ekerwin** [comment]
That proxy configuration is unfortunate - we will try and get that fixed ASAP.

As for the certificate/keystore interaction, what is the concern? As I see it, you first must update your own keystore to trust the Black Duck server to even download the scan cli. Then, after the download, we copy that trusted certificate into the embedded keystore of the scan cli.

If you don't trust the Black Duck server, you won't get the scan cli. If you do trust the Black Duck server, shouldn't the scan cli also trust it?

**Comment by tlorenz-reply** [comment]
just wondered why it is necessary as you have to trust the server anyway and if you do it there is no need to put the certificate into the keystore, is there?

**Comment by ekerwin** [comment]
There is an embedded keystore in what you download from the Black Duck server. That keystore does not, by default, trust the server it was downloaded from. My team thinks that it should, but we haven't been able to get that changed in the product. So you, the customer, trust the server in YOUR keystore, but the server is not trusted in OUR keystore without this code.

**Comment by tlorenz-reply** [comment]
But that is only necessary if you download a java runtime, isn't it? 
We set BDS_JAVA_HOME because we run on alpine linux where the downloaded JRE doesn't run and then there should be no need to download the certificate

**Comment by ekerwin** [comment]
No matter what, a java runtime IS downloaded. In your case, we improve the downloaded java runtime needlessly since you don't use it. But most users are not in this group.

So if you're unhappy about the extra downloading of the certificate and additional processing on an unused java runtime, I can appreciate that, but we didn't want to add special code to handle the BDS_JAVA_HOME case since I didn't think the code was worth it.

The concern was with toggling usage of BDS_JAVA_HOME. While you can't avoid it because of alpine, other users can toggle it back and forth. We wanted to make the downloaded java runtime, if you were ever to use it, work against the server it was downloaded from.

**Comment by tlorenz-reply** [comment]
at the moment I am just a little bit unhappy about the direct connection which causes a delay and shows up a connect timeout exception in the logs afterwards

**Comment by ekerwin** [comment]
And that is a clear bug that must be addressed. :)

**Comment by akamen** [comment]
@tlorenz-reply just curious, do you use blackduck-common in your environment or is this via another one of our integrations?

**Comment by tlorenz-reply** [comment]
We are calling detect.sh in a Kubernetes pod to scan an image tar file.

**Comment by ekerwin** [comment]
This is fixed in the latest release of blackduck-common.
